filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/www/html/storage/logs/*.log
    multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
    multiline.negate: true
    multiline.match: after
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message
    fields:
      log_type: app
      source: laravel
      environment: local 
    fields_under_root: true
    tags: ["laravel", "application"]
    close_inactive: 1h
    scan_frequency: 10s

  # - type: log
  #   enabled: true
  #   paths:
  #     - /var/www/html/storage/logs/volume-bot-monitor.log
  #   json.keys_under_root: true
  #   json.add_error_key: true
  #   json.message_key: message
  #   fields:
  #     log_type: bot
  #     source: volume-bot
  #   fields_under_root: true
  #   tags: ["volume-bot", "monitor"]

  # - type: log
  #   enabled: true
  #   paths:
  #     - /var/www/html/storage/logs/worker.log*
  #   json.keys_under_root: true
  #   json.add_error_key: true
  #   json.message_key: message
  #   fields:
  #     log_type: worker
  #     source: queue
  #   fields_under_root: true
  #   tags: ["worker", "queue"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - decode_json_fields:
      fields: ["message", "context"]
      process_array: false
      max_depth: 1
      target: ""
      overwrite_keys: true
  - add_fields:
      target: ""
      fields:
        filebeat_source: "laravel_logs"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "app-logs-%{+yyyy.MM.dd}"
  bulk_max_size: 50
  timeout: 90
  
setup.template.enabled: false 
setup.ilm.enabled: false

setup.use_data_streams: false

setup.kibana:
  host: "kibana:5601"

logging.json: true
logging.level: info